name: Release

on:
  release:
    types: [released]

jobs:
  publish-release:

    runs-on: ubuntu-latest

    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write

    steps:
    - uses: actions/checkout@v4

    - name: Get version
      run: |
        echo "VERSION=$(/usr/bin/git tag --list | sed 's|.*v\([0-9\.]*\).*|\1|')" >> $GITHUB_ENV
    - name: Bump version
      run: |
        sed 's/^version = ".*"/version = "'"$VERSION"'"/' -i pyproject.toml

    - name: Update Changelog
      uses: stefanzweifel/changelog-updater-action@v1
      with:
        latest-version: ${{ github.event.release.tag_name }}
        release-notes: ${{ github.event.release.body }}

    - name: Commit changes
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        branch: main
        commit_user_name: HDate Release Bot
        commit_user_email: hdate+github-actions[bot]@users.noreply.github.com
        commit_message: Release ${{ github.event.release.tag_name }}

    - name: Set up PDM
      uses: pdm-project/setup-pdm@v4

    - name: Build and publish to pypi
      run: pdm publish --repository testpypi
      env:
        PDM_PUBLISH_PASSWORD: ${{ secrets.TEST_PYPI_PASSWORD }}
