name: Release

on:
  release:
    types: [released]

jobs:
  publish-release:

    runs-on: ubuntu-latest

    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write

    steps:
    - uses: actions/checkout@v4

    - name: Get version
      run: |
        echo "VERSION=$(/usr/bin/git tag --list | sed 's|.*v\([0-9\.]*\).*|\1|')" >> $GITHUB_ENV
    - name: Bump version
      run: |
        sed 's/^version = ".*"/version = "'"$VERSION"'"/' -i pyproject.toml

    - name: Update Changelog
      uses: stefanzweifel/changelog-updater-action@v1
      with:
        latest-version: ${{ github.event.release.tag_name }}
        release-notes: ${{ github.event.release.body }}

    - name: Commit changes
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        branch: release-${{ github.event.release.tag_name }}
        commit_user_name: HDate Release Bot
        commit_user_email: hdate+github-actions[bot]@users.noreply.github.com
        commit_message: Release ${{ github.event.release.tag_name }}
        create_branch: true

    - name: Create Pull Request
      id: create-pr
      uses: peter-evans/create-pull-request@v6
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        branch: release-${{ github.event.release.tag_name }}
        title: Release ${{ github.event.release.tag_name }}
        body: |
          Changelog: ${{ github.event.release.body }}
          - Auto generated from [release.yaml](https://github.com/py-libhdate/py-libhdate/tree/main/.github/workflows/release.yaml)
        base: main

    - name: Enable Pull Request Automerge
      uses: peter-evans/enable-pull-request-automerge@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        pull-request-number: ${{ steps.create-pr.outputs.pull-request-number }}
        merge-method: squash

    - name: Set up PDM
      uses: pdm-project/setup-pdm@v4

    - name: Build and publish to pypi
      run: pdm publish --repository testpypi
      env:
        PDM_PUBLISH_PASSWORD: ${{ secrets.TEST_PYPI_PASSWORD }}
